# Generated by Django 5.2.1 on 2025-05-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='transaction_category',
            field=models.CharField(choices=[('Income', 'Income'), ('Expenses', 'Expenses')], default='Others', max_length=30),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_type',
            field=models.CharField(choices=[('Salary', 'Salary'), ('Grocery', 'Grocery'), ('Entertainment', 'Entertainment'), ('Fashion', 'Fashion')], max_length=30),
        ),
    ]
