# Generated by Django 5.2.1 on 2025-05-14 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_transactions_transaction_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='date',
            new_name='month',
        ),
    ]
